repos:
  - repo: local
    hooks:
      - id: make-format
        name: Make Format
        entry: make format
        language: system
        pass_filenames: false
        always_run: true

      - id: make-check
        name: Make Check
        entry: make check
        language: system
        pass_filenames: false
        always_run: true

      - id: make-test
        name: Make Test
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
  
