repos:
  - repo: local
    hooks:
      - id: check
        name: Static code analysis
        entry: make check
        language: system
        pass_filenames: false
        always_run: true

      - id: test
        name: Unit tests
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
  
