[project]
name = "sofes"
version = "0.0.1"
authors = [
  { name="mlojek", email="marcin.lojek@pw.edu.pl" },
]
description = "Surrogate objective function for evolution strategy utils"
readme = "README.md"
requires-python = ">=3.11.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "github.com/mlojek/sofes"