"""
Point dataclass, representing a point in the search space.
"""

import numpy as np
from pydantic import BaseModel, ConfigDict, field_validator


class Point(BaseModel):
    """
    Point dataclass, representing a point in the search space.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    x: np.ndarray | None
    "1D vector representing the point from the search space"

    y: float | None = None
    "Function value for this point."

    is_evaluated: bool = False
    "Wheather the value was generated by the objective function."

    @field_validator("x", mode="before")
    @classmethod
    def _coerce_x(cls, v: object) -> np.ndarray | None:
        if v is not None:
            return np.asarray(v, dtype=np.float64)
        return None

    def dim(self) -> int:
        """
        Return the dimensionality of the point.

        Returns:
            Dimensionality of the point, equal to length of x.
        """
        assert self.x is not None
        return len(self.x)

    def remove_x(self) -> None:
        """
        Set x to None. This is done mostly to save memory and storage space since x is rarely used.
        """
        self.x = None

    def __eq__(self, other: object) -> bool:
        """
        Compare with other point. Points are considered equal if their x values are equal.
        Other properites are not compared.

        Args:
            other: Another instance of Point class.

        Returns:
            True if x values of self and other are equal, False otherwise.
        """
        if not isinstance(other, Point):
            return NotImplemented
        assert self.x is not None
        assert other.x is not None
        return bool(np.array_equal(self.x, other.x))
