"""
Point and PointList classes
"""

from dataclasses import dataclass
from typing import Any, Dict, List

import numpy as np


@dataclass
class Point:
    """
    Point dataclass, representing a point in the search space.
    """

    x: np.ndarray
    "1D vector representing the point from the search space"

    y: float = None
    "Function value for this point."

    is_evaluated: bool = False
    "Wheather the value was generated by the objective function."


@dataclass
class PointList:
    """
    Class holding a list of points. Might be used as optimization run result log
    or as a train set for surrogate function.
    """

    points: List[Point]
    "The list of points"

    def only_evaluated(self) -> List[Point]:
        """
        Return list of only those points that have been evaluated.

        Returns:
            List[Point]: List containing evaluated points.
        """
        return filter(lambda point: point.is_evaluated, self.points)

    def __getitem__(self, index: int) -> Point:
        """
        Allows to index this object like a list.

        Args:
            index (int): The index of object to fetch.

        Returns:
            Point: The object at given index.
        """
        return self.points[index]

    def __len__(self) -> int:
        """
        Return number of points stored in the list.

        Returns:
            int: Number of points stored in the list.
        """
        return len(self.points)


@dataclass
class Bounds:
    """
    Class representing bounds of the search space.
    """

    lower: float
    "The lower bound of search space."

    upper: float
    "The upper bound of search space."

    def to_list(self) -> List[float]:
        """
        Return the bounds as a list of two floats.

        Returns:
            List[float]: List containing the lower and upper bound.
        """
        return [self.lower, self.upper]


@dataclass
class OptimizerMetadata:
    """
    Metadata of an optimizer model.
    """

    name: str
    "Name of the optimizer."

    population_size: int
    "Number of points generated in each generation."

    hyperparameters: Dict[str, Any] = None
    "Other hyperparameters of the optimizer, optional."


@dataclass
class FunctionMetadata:
    """
    Metadata of objective function.
    """

    name: str
    "Name of the function."

    dim: int
    "Dimensionality of the function."

    hyperparameters: Dict[str, Any] = None
    "Other hyperparameters of the function, optional."


@dataclass
class OptimizationRun:
    """
    Dataclass containing information about an optimization run. Stores metadata of optimization
    method and objective function as well as point logs for multiple runs.
    """

    model_metadata: OptimizerMetadata
    "Metadata describing the model used in optimization."

    function_metadata: FunctionMetadata
    "Metadata describing the optimized function."

    bounds: Bounds
    "Bounds of the search space."

    logs: List[PointList]
    "Logs of points from the optimization runs."
