name: CI

on:
  push:
    branches:
      - main
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: python setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: dependencies installation
        run: |
          python -m pip install --upgrade pip
          make install
          make clean

      - name: static code analysis
        run: make check

      - name: unit tests
        run: make test
