name: CI

on:
  push:
    branches:
      - main
      - '**' # Runs on any branch push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: python setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: dependencies installation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: src static code analysis
        run: make check-src

      - name: unit tests
        run: make test
